/* Parameters, dude */
debug: false
input:
  cloud_file: data/talstrasse/hololens.pcd
  trajectory_file: data/talstrasse/traj
  floorplan_file: data/talstrasse/talstrasse.jpeg
parameters:
  poisson_depth: 6
  normal_search_radius: 0.5
  outlier_radius: 3
  outlier_min_neighbours: 10
  image_resolution: 0.0694 // [m/px]
  pass_xlim_min: -13.0
  pass_xlim_max: 24.0
  pass_ylim_min: -15.0
  pass_ylim_max: 25.0